name: CICD
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519_impisigmatus
          chmod 600 ~/.ssh/id_ed25519_impisigmatus
          cat >> ~/.ssh/config << END
          Host impisigmatus
            HostName $SSH_HOSTNAME
            User $SSH_USERNAME
            IdentityFile ~/.ssh/id_ed25519_impisigmatus
            StrictHostKeyChecking no
          END

      - name: Clone
        run: ssh impisigmatus 'rm -rf compose/ && git clone https://github.com/Impisigmatus/compose.git'

      - name: Run
        run: |
          echo "Output:" > out.data
          echo "pwd: $(pwd)" >> out.data
          echo "ls: $(ls)" >> out.data
          ssh impisigmatus 'cd compose'
          echo "pwd: $(pwd)" >> out.data
          echo "ls: $(ls)" >> out.data
          ssh impisigmatus './compose.sh'
